version: "3.8"
services:
  nginx:
    image: 810731456698.dkr.ecr.us-east-2.amazonaws.com/nginx_stage
    restart: always
    # build:
    #   context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - server
    links:
      - web
      - server
    # networks:
    #   - QAnetwork
  web:
    image: 810731456698.dkr.ecr.us-east-2.amazonaws.com/qa-staging-web
    container_name: web
    # build:
    #   context: ./web
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./web:/web/src/app
      - web/src/app/node_modules
      - web/src/app/.next
    entrypoint: ["yarn", "start"]
  server:
    image: 810731456698.dkr.ecr.us-east-2.amazonaws.com/qa-staging-server
    container_name: server
    # build:
    #   context: ./server
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./server:/server/src/app
      - /server/src/app/node_modules
      - /server/src/app/dist
    entrypoint: ["node", "dist/index.js"]
networks:
  default:
    external: true
    name: QAnetwork
