FROM node:14.16.0

# Create app directory
WORKDIR /server/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./
COPY yarn.lock ./

RUN yarn 

COPY . .
COPY  .env ./

RUN npm run build

ENV NODE_ENV production

EXPOSE 4000
CMD [ "node", "dist/index.js" ]
USER node


# FROM nginx
# EXPOSE 4000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY ./dist /usr/share/nginx/html


